/**
 * $Id: initMockups.js,v 1.5 2013/02/11 12:14:28 mate Exp $
 * Copyright (c) 2006-2012, JGraph Ltd
 */
var mxMockupC =
{
		BAR_HEIGHT : 'barHeight',
		BAR_POS : 'barPos',
		BG_STYLE : 'bgStyle',
		BG_FLAT_GREEN : 'bgGreen',
		BG_FLAT_WHITE : 'bgWhite',
		BG_FLAT_GRAY : 'bgGray',
		BG_FLAT_CUSTOM : 'bgFlat',
		BG_MAP : 'bgMap',
		BG_STRIPED : 'bgStriped',
		BUTTON_STYLE : 'buttonStyle',
		BUTTON_TEXT : 'buttonText',
		BUTTON_STATE : 'buttonState',
		CHEVRON : 'chevron',
		GRID_SIZE : 'gridSize',
		POINTER_BOTTOM : 'bottom',
		POINTER_POS : 'pointerPos',
		POINTER_TOP : 'top',
		ROUND : 'round',
		SELECTED : '+', 		//has to be one character long
		STATE_ON : 'on',
		STATE_OFF : 'off',
		SUB_TEXT : 'subText',
		TAB_BLOCK : 'block',
		TAB_CONE : 'cone',
		TAB_HALF_CONE : 'halfCone',
		TAB_ROUND : 'round',
		TAB_STYLE: 'tabStyle',
		
		SHAPE_ACCORDION : 'mxgraph.mockupContainers.accordion',
		SHAPE_BREADCRUMB : 'mxgraph.mockupNavigation.breadcrumb',
		SHAPE_BROWSER_WINDOW : 'mxgraph.mockupContainers.browserWindow',
		SHAPE_BUTTON : 'mxgraph.mockupButtons.button',
		SHAPE_GROUP : 'mxgraph.mockupContainers.group',
		SHAPE_HOR_BUTTON_BAR : 'mxgraph.mockupButtons.horButtonBar',
		SHAPE_HOR_CURLY_BRACE : 'mxgraph.mockupMarkup.horCurlyBrace',
		SHAPE_HOR_TAB_BAR : 'mxgraph.mockupMarkup.horTabBar',
		SHAPE_MULTILINE_BUTTON : 'mxgraph.mockupButtons.multilineButton',
		SHAPE_STEP_BAR : 'mxgraph.mockupNavigation.stepBar',
		SHAPE_VER_BUTTON_BAR : 'mxgraph.mockupButtons.verButtonBar',
		SHAPE_VIDEO_PLAYER : 'mxgraph.mockupContainers.VideoPlayer',
		SHAPE_USER_FEMALE : 'mxgraph.mockupContainers.userFemale',
		SHAPE_USER_MALE : 'mxgraph.mockupContainers.userMale',
		SHAPE_WINDOW : 'mxgraph.mockupContainers.window',

		SHAPE_IADD_ICON : 'mxgraph.mockupios.iAddIcon',
		SHAPE_IALERT_BOX : 'mxgraph.mockupios.iAlertBox',
		SHAPE_IALPHA_LIST : 'mxgraph.mockupios.iAlphaList',
		SHAPE_IAPP_BAR : 'mxgraph.mockupios.iAppBar',
		SHAPE_IARROW_ICON : 'mxgraph.mockupios.iArrowIcon',
		SHAPE_IBG_FLAT : 'mxgraph.mockupios.iBgFlat',
		SHAPE_IBG_MAP : 'mxgraph.mockupios.iBgMap',
		SHAPE_IBG_STRIPED : 'mxgraph.mockupios.iBgStriped',
		SHAPE_IBUTTON : 'mxgraph.mockupios.iButton',
		SHAPE_IBUTTON_BACK : 'mxgraph.mockupios.iButtonBack',
		SHAPE_IBUTTON_FORWARD : 'mxgraph.mockupios.iButtonFw',
		SHAPE_IBUTTON_BAR : 'mxgraph.mockupios.iButtonBar',
		SHAPE_ICALL_BUTTONS : 'mxgraph.mockupios.iCallButtons',
		SHAPE_ICALL_DIALOG : 'mxgraph.mockupios.iCallDialog',
		SHAPE_ICHECKBOX_GROUP : 'mxgraph.mockupios.iCheckboxGroup',
		SHAPE_ICHECK_ICON : 'mxgraph.mockupios.iCheckIcon',
		SHAPE_ICLOUD_PROGRESS_BAR : 'mxgraph.mockupios.iCloudProgressBar',
		SHAPE_ICOMBO_BOX : 'mxgraph.mockupios.iComboBox',
		SHAPE_ICOPY : 'mxgraph.mockupios.iCopy',
		SHAPE_ICOPY_AREA : 'mxgraph.mockupios.iCopyArea',
		SHAPE_IICON_GRID : 'mxgraph.mockupios.iIconGrid',
		SHAPE_IDELETE_APP : 'mxgraph.mockupios.iDeleteApp',
		SHAPE_IDELETE_ICON : 'mxgraph.mockupios.iDeleteIcon',
		SHAPE_IDOWNLOAD_BAR : 'mxgraph.mockupios.iDownloadBar',
		SHAPE_IDIALOG_BOX : 'mxgraph.mockupios.iDialogBox',
		SHAPE_IDIRECTION : 'mxgraph.mockupios.iDir',
		SHAPE_IHOME_PAGE_CONTROL : 'mxgraph.mockupios.iHomePageControl',
		SHAPE_IKEYB_LETTERS : 'mxgraph.mockupios.iKeybLett',
		SHAPE_IKEYB_NUMBERS : 'mxgraph.mockupios.iKeybNumb',
		SHAPE_IKEYB_SYMBOLS : 'mxgraph.mockupios.iKeybSymb',
		SHAPE_ILOCATION_BAR : 'mxgraph.mockupios.iLocBar',
		SHAPE_ILOCK_BUTTON : 'mxgraph.mockupios.iLockButton',
		SHAPE_IHOR_BUTTON_BAR : 'mxgraph.mockupios.iHorButtonBar',
		SHAPE_IINFO_ICON : 'mxgraph.mockupios.iInfoIcon',
		SHAPE_ION_OFF_BUTTON : 'mxgraph.mockupios.iOnOffButton',
		SHAPE_IOPTION : 'mxgraph.mockupios.iOption',
		SHAPE_IPAGE_CONTROL : 'mxgraph.mockupios.iPageControl',
		SHAPE_IPAD : 'mxgraph.mockupios.iPad',
		SHAPE_IPHONE : 'mxgraph.mockupios.iPhone',
		SHAPE_IPIN : 'mxgraph.mockupios.iPin',
		SHAPE_IPREV_NEXT : 'mxgraph.mockupios.iPrevNext',
		SHAPE_IPROGRESS_BAR : 'mxgraph.mockupios.iProgressBar',
		SHAPE_IRADIO_GROUP : 'mxgraph.mockupios.iRadioGroup',
		SHAPE_ISLIDER : 'mxgraph.mockupios.iSlider',
		SHAPE_ISORT_FIND_ICON : 'mxgraph.mockupios.iSortFindIcon',
		SHAPE_ITEXT_INPUT : 'mxgraph.mockupios.iTextInput',
		SHAPE_ITOP_BAR : 'mxgraph.mockupios.iTopBar',
		SHAPE_ITOP_BAR_LOCKED : 'mxgraph.mockupios.iTopBarLocked',
		SHAPE_IURL_BAR : 'mxgraph.mockupios.iURLBar',
		SHAPE_IVIDEO_CONTROLS : 'mxgraph.mockupios.iVideoControls',
		SHAPE_ISCREEN_NAME_BAR: 'mxgraph.mockupios.iScreenNameBar',
			
		STYLE_FILLCOLOR2 : 'fillColor2',
		STYLE_FILLCOLOR3 : 'fillColor3',
		STYLE_TEXTCOLOR : 'textColor',
		STYLE_TEXTCOLOR2 : 'textColor2',
		STYLE_TEXTSIZE : 'textSize',
		STYLE_STROKECOLOR2 : 'strokeColor2',
		STYLE_STROKECOLOR3 : 'strokeColor3'
};