(function()
{
	//Adds custom shape library
	var SidebarInit = Sidebar.prototype.init;
	Sidebar.prototype.init = function()
	{
		SidebarInit.apply(this, arguments);

		mxResources.parse('mockupContainers=Mockup / Containers');
		mxResources.parse(mxShapeMockupVideoPlayer.prototype.cst.SHAPE_VIDEO_PLAYER + '=Video Player');
		mxResources.parse(mxShapeMockupAccordion.prototype.cst.SHAPE_ACCORDION + '=Accordion');
		mxResources.parse(mxShapeMockupBrowserWindow.prototype.cst.SHAPE_BROWSER_WINDOW + '=Browser Window');
		mxResources.parse(mxShapeMockupUserMale.prototype.cst.SHAPE_MALE_USER + '=User, Male');
		mxResources.parse(mxShapeMockupUserFemale.prototype.cst.SHAPE_FEMALE_USER + '=User, Female');
		mxResources.parse(mxShapeMockupGroup.prototype.cst.SHAPE_GROUP + '=Group');
		mxResources.parse(mxShapeMockupWindow.prototype.cst.SHAPE_WINDOW + '=Window');
		mxResources.parse(mxShapeMockupHorTabBar.prototype.cst.SHAPE_HOR_TAB_BAR + '=Horizontal Tab Bar');
		mxResources.parse(mxShapeMockupVerTabBar.prototype.cst.SHAPE_VER_TAB_BAR + '=Vertical Tab Bar');
		mxResources.parse(mxShapeMockupAlertBox.prototype.cst.SHAPE_ALERT_BOX + '=Alert Box');
			
		this.addPalette('mockupContainers', 'Mockup Containers (Test)', false, mxUtils.bind(this, function(content)
		{
			var s = mxConstants.STYLE_VERTICAL_LABEL_POSITION + '=bottom;' + mxConstants.STYLE_VERTICAL_ALIGN + '=top;' + mxConstants.STYLE_STROKEWIDTH + '=1;';

			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupVideoPlayer.prototype.cst.SHAPE_VIDEO_PLAYER + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxShapeMockupVideoPlayer.prototype.cst.STROKE_COLOR2 + '=#008cff;' + mxShapeMockupVideoPlayer.prototype.cst.STROKE_COLOR3 + '=#c4c4c4;' + mxShapeMockupVideoPlayer.prototype.cst.TEXT_COLOR + '=#666666;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupVideoPlayer.prototype.cst.FILL_COLOR2 + '=#008cff;' + mxShapeMockupVideoPlayer.prototype.cst.BAR_HEIGHT + '=30;' + mxShapeMockupVideoPlayer.prototype.cst.BAR_POS + '=20;', 300, 200, '', 'Video Player', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupAccordion.prototype.cst.SHAPE_ACCORDION + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxShapeMockupAccordion.prototype.cst.STROKE_COLOR2 + '=#c4c4c4;' + mxShapeMockupAccordion.prototype.cst.TEXT_COLOR + '=#666666;' + mxShapeMockupAccordion.prototype.cst.TEXT_COLOR2 + '=#ffffff;' + mxShapeMockupAccordion.prototype.cst.MAIN_TEXT + '=Group 1,Group 2,+Group 3,Group 4;' + mxShapeMockupAccordion.prototype.cst.TEXT_SIZE + '=17;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupAccordion.prototype.cst.FILL_COLOR2 + '=#008cff', 100, 220, '', 'Accordion', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupBrowserWindow.prototype.cst.SHAPE_BROWSER_WINDOW + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxShapeMockupBrowserWindow.prototype.cst.STROKE_COLOR2 + '=#008cff;' + mxShapeMockupBrowserWindow.prototype.cst.STROKE_COLOR3 + '=#c4c4c4;' + mxShapeMockupBrowserWindow.prototype.cst.TEXT_COLOR + '=#666666;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;', 550, 380, '', 'Browser Window', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupUserMale.prototype.cst.SHAPE_MALE_USER + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxShapeMockupUserMale.prototype.cst.STROKE_COLOR2 + '=#008cff;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;', 100, 100, '', 'User, Male', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupUserFemale.prototype.cst.SHAPE_FEMALE_USER + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxShapeMockupUserFemale.prototype.cst.STROKE_COLOR2 + '=#008cff;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;', 100, 100, '', 'User, Female', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupGroup.prototype.cst.SHAPE_GROUP + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupGroup.prototype.cst.FILL_COLOR2 + '=#008cff;' + mxShapeMockupGroup.prototype.cst.TEXT_SIZE + '=17;' + mxShapeMockupGroup.prototype.cst.MAIN_TEXT + '=Group;' + mxShapeMockupGroup.prototype.cst.TEXT_COLOR + "=#ffffff;", 150, 200, '', 'Group', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupWindow.prototype.cst.SHAPE_WINDOW + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxShapeMockupWindow.prototype.cst.STROKE_COLOR2 + '=#008cff;' + mxShapeMockupWindow.prototype.cst.STROKE_COLOR3 + '=#c4c4c4;' + mxShapeMockupWindow.prototype.cst.TEXT_COLOR + '=#666666;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupWindow.prototype.cst.MAIN_TEXT + '=Window Title;' + mxShapeMockupWindow.prototype.cst.TEXT_SIZE + '=17;', 550, 380, '', 'Window', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupHorTabBar.prototype.cst.SHAPE_HOR_TAB_BAR + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxShapeMockupHorTabBar.prototype.cst.STYLE_FILLCOLOR2 + '=#008cff;' + mxShapeMockupHorTabBar.prototype.cst.TEXT_COLOR + '=#666666;' + mxShapeMockupHorTabBar.prototype.cst.SEL_TEXT_COLOR + '=#ffffff;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupHorTabBar.prototype.cst.TAB_NAMES + '=Tab 1,+Tab 2,Tab 3;' + mxShapeMockupHorTabBar.prototype.cst.TEXT_SIZE + '=17;' + mxShapeMockupHorTabBar.prototype.cst.TAB_STYLE + '=' + mxShapeMockupHorTabBar.prototype.cst.BLOCK + ';', 400, 200, '', 'Horizontal Tab Bar', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupVerTabBar.prototype.cst.SHAPE_VER_TAB_BAR + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxShapeMockupVerTabBar.prototype.cst.STYLE_FILLCOLOR2 + '=#008cff;' + mxShapeMockupVerTabBar.prototype.cst.TEXT_COLOR + '=#666666;' + mxShapeMockupVerTabBar.prototype.cst.SEL_TEXT_COLOR + '=#ffffff;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupVerTabBar.prototype.cst.TAB_NAMES + '=Tab 1,+Tab 2,Tab 3;' + mxShapeMockupVerTabBar.prototype.cst.TEXT_SIZE + '=17;' + mxShapeMockupVerTabBar.prototype.cst.TAB_STYLE + '=' + mxShapeMockupVerTabBar.prototype.cst.BLOCK + ';', 400, 200, '', 'Vertical Tab Bar', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupAlertBox.prototype.cst.SHAPE_ALERT_BOX + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxShapeMockupAlertBox.prototype.cst.STROKE_COLOR2 + '=#008cff;' + mxShapeMockupAlertBox.prototype.cst.STROKE_COLOR3 + '=#c4c4c4;' + mxShapeMockupAlertBox.prototype.cst.TEXT_COLOR + '=#666666;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupAlertBox.prototype.cst.MAIN_TEXT + '=Dialog Title;' + mxShapeMockupAlertBox.prototype.cst.SUB_TEXT + '=Dialog text line 1,Dialog text line 2;'+ mxShapeMockupAlertBox.prototype.cst.BUTTON_TEXT + '=Cancel,OK;' + mxShapeMockupAlertBox.prototype.cst.TEXT_SIZE + '=17;', 250, 140, '', 'Dialog Box', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupAlertBox.prototype.cst.SHAPE_ALERT_BOX + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxShapeMockupAlertBox.prototype.cst.STROKE_COLOR2 + '=#008cff;' + mxShapeMockupAlertBox.prototype.cst.STROKE_COLOR3 + '=#c4c4c4;' + mxShapeMockupAlertBox.prototype.cst.TEXT_COLOR + '=#666666;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupAlertBox.prototype.cst.MAIN_TEXT + '=Message Title;' + mxShapeMockupAlertBox.prototype.cst.SUB_TEXT + '=Message text line 1,Message text line 2,Message text line 3;'+ mxShapeMockupAlertBox.prototype.cst.BUTTON_TEXT + '=OK;' + mxShapeMockupAlertBox.prototype.cst.TEXT_SIZE + '=17;', 250, 160, '', 'Message Box', false));
		}));
	};
})();
