(function()
{
	//Adds custom shape library
	var SidebarInit = Sidebar.prototype.init;
	
	Sidebar.prototype.init = function()
	{
		SidebarInit.apply(this, arguments);

		mxResources.parse('forms=Forms');
		mxResources.parse(mxShapeMockupCheckboxGroup.prototype.cst.SHAPE_CHECKBOX_GROUP + '=Checkbox Group');
		mxResources.parse(mxShapeMockupRadioGroup.prototype.cst.SHAPE_RADIO_GROUP + '=Radiobutton Group');
		mxResources.parse(mxShapeMockupColorPicker.prototype.cst.SHAPE_COLOR_PICKER + '=Color Picker');
		mxResources.parse(mxShapeMockupComboBox.prototype.cst.SHAPE_COMBO_BOX + '=Combo Box');
		mxResources.parse(mxShapeMockupSpinner.prototype.cst.SHAPE_SPINNER + '=Spinner');
		mxResources.parse(mxShapeMockupMenuBar.prototype.cst.SHAPE_MENU_BAR + '=Menu Bar');
		mxResources.parse(mxShapeMockupHorSlider.prototype.cst.SHAPE_HOR_SLIDER + '=Horizontal Slider');
		mxResources.parse(mxShapeMockupListBox.prototype.cst.SHAPE_LIST_BOX + '=List Box');
		mxResources.parse(mxShapeMockupPwField.prototype.cst.SHAPE_PW_FIELD + '=Password Field');
		mxResources.parse(mxShapeMockupSplitter.prototype.cst.SHAPE_SPLITTER + '=Splitter');
		mxResources.parse(mxShapeMockupWedgeBar.prototype.cst.SHAPE_WEDGE_BAR + '=Wedge Bar');
		mxResources.parse(mxShapeMockupSearchBox.prototype.cst.SHAPE_SEARCH_BOX + '=Search Box');
		mxResources.parse(mxShapeMockupSignIn.prototype.cst.SHAPE_SIGN_IN + '=Sign In');
		mxResources.parse(mxShapeMockupCalendar.prototype.cst.SHAPE_CALENDAR + '=Calendar');
			
		this.addPalette('forms', 'Mockup Forms (Test)', false, mxUtils.bind(this, function(content)
		{
			var s = mxConstants.STYLE_VERTICAL_LABEL_POSITION + '=bottom;' + mxConstants.STYLE_VERTICAL_ALIGN + '=top;' + mxConstants.STYLE_STROKEWIDTH + '=1;';

			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupCheckboxGroup.prototype.cst.SHAPE_CHECKBOX_GROUP + ';' + mxConstants.STYLE_STROKECOLOR + '=none;' + mxShapeMockupCheckboxGroup.prototype.cst.TEXT_COLOR + '=#666666,#008cff;' + mxShapeMockupCheckboxGroup.prototype.cst.MAIN_TEXT + '=Option 1;' + mxConstants.STYLE_FONTSIZE + '=17;' + mxConstants.STYLE_FILLCOLOR + '=none;', 150, 30, '', 'Checkbox', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupCheckboxGroup.prototype.cst.SHAPE_CHECKBOX_GROUP + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxShapeMockupCheckboxGroup.prototype.cst.TEXT_COLOR + '=#666666,#008cff;' + mxShapeMockupCheckboxGroup.prototype.cst.MAIN_TEXT + '=Setting 1,Setting 2,+Setting 3,Setting 4;' + mxConstants.STYLE_FONTSIZE + '=17;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;', 150, 120, '', 'Checkbox Group', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupRadioGroup.prototype.cst.SHAPE_RADIO_GROUP + ';' + mxConstants.STYLE_STROKECOLOR + '=none;' + mxShapeMockupRadioGroup.prototype.cst.TEXT_COLOR + '=#666666,#008cff;' + mxShapeMockupRadioGroup.prototype.cst.MAIN_TEXT + '=Option 1;' + mxConstants.STYLE_FONTSIZE + '=17;' + mxConstants.STYLE_FILLCOLOR + '=none;', 150, 30, '', 'Radiobutton', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupRadioGroup.prototype.cst.SHAPE_RADIO_GROUP + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxShapeMockupRadioGroup.prototype.cst.TEXT_COLOR + '=#666666,#008cff;' + mxShapeMockupRadioGroup.prototype.cst.MAIN_TEXT + '=Setting 1,Setting 2,+Setting 3,Setting 4;' + mxConstants.STYLE_FONTSIZE + '=17;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;', 150, 120, '', 'Radiobutton Group', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupColorPicker.prototype.cst.SHAPE_COLOR_PICKER + ';' + mxShapeMockupColorPicker.prototype.cst.COLOR + '=#aaddff;', 40, 40, '', 'Color Picker', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupComboBox.prototype.cst.SHAPE_COMBO_BOX + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxConstants.STYLE_FILLCOLOR + '=#ddeeff;' + mxShapeMockupComboBox.prototype.cst.FILL_COLOR2 + '=#aaddff;' + mxShapeMockupComboBox.prototype.cst.MAIN_TEXT + '=Option 1;' + mxShapeMockupComboBox.prototype.cst.TEXT_COLOR + '=#666666;' + mxShapeMockupComboBox.prototype.cst.TEXT_SIZE + '=17;', 150, 30, '', 'Combo Box', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupSpinner.prototype.cst.SHAPE_SPINNER + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxShapeMockupSpinner.prototype.cst.LAYOUT + '=' + mxShapeMockupSpinner.prototype.cst.LAYOUT_RIGHT + ';' + mxShapeMockupSpinner.prototype.cst.SPINNER_STYLE + '=' + mxShapeMockupSpinner.prototype.cst.SPINNER_NORMAL + ';' + mxShapeMockupSpinner.prototype.cst.ADJ_STYLE + '=' + mxShapeMockupSpinner.prototype.cst.ADJ_TRIANGLE + ';' + mxConstants.STYLE_FILLCOLOR + '=#aaddff;' + mxShapeMockupSpinner.prototype.cst.TEXT_SIZE + '=17;' + mxShapeMockupSpinner.prototype.cst.TEXT_COLOR + '=#666666;', 150, 60, '', 'Spinner', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupMenuBar.prototype.cst.SHAPE_MENU_BAR + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxShapeMockupMenuBar.prototype.cst.STROKE_COLOR2 + '=#c4c4c4;' + mxShapeMockupMenuBar.prototype.cst.TEXT_COLOR + '=#666666;' + mxShapeMockupMenuBar.prototype.cst.TEXT_COLOR2 + '=#ffffff;' + mxShapeMockupMenuBar.prototype.cst.MAIN_TEXT + '=File,Edit,Options,Tools,Window,Help;' + mxShapeMockupMenuBar.prototype.cst.TEXT_SIZE + '=17;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupMenuBar.prototype.cst.FILL_COLOR2 + '=#008cff', 500, 30, '', 'Menu Bar', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupHorSlider.prototype.cst.SHAPE_HOR_SLIDER + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupHorSlider.prototype.cst.STYLE + '=' + mxShapeMockupHorSlider.prototype.cst.SLIDER_BASIC + ';' + mxShapeMockupHorSlider.prototype.cst.SLIDER_POS + '=20;' + mxShapeMockupHorSlider.prototype.cst.HANDLE_STYLE + '=' + mxShapeMockupHorSlider.prototype.cst.HANDLE_CIRCLE + ';' + mxShapeMockupHorSlider.prototype.cst.FILL_COLOR2 + '=#ddeeff;', 150, 30, '', 'Horizontal Slider', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupHorSlider.prototype.cst.SHAPE_HOR_SLIDER + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupHorSlider.prototype.cst.STYLE + '=' + mxShapeMockupHorSlider.prototype.cst.SLIDER_BASIC + ';' + mxShapeMockupHorSlider.prototype.cst.SLIDER_POS + '=20;' + mxShapeMockupHorSlider.prototype.cst.HANDLE_STYLE + '=' + mxShapeMockupHorSlider.prototype.cst.HANDLE_CIRCLE + ';' + mxShapeMockupHorSlider.prototype.cst.FILL_COLOR2 + '=#ddeeff;' + mxConstants.STYLE_DIRECTION + '=' + mxConstants.DIRECTION_NORTH + ';', 30, 150, '', 'Vertical Slider', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupListBox.prototype.cst.SHAPE_LIST_BOX + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxShapeMockupListBox.prototype.cst.TEXT_COLOR + '=#666666,#008cff;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupListBox.prototype.cst.MAIN_TEXT + '=Title;' + mxShapeMockupListBox.prototype.cst.SUB_TEXT + '=Item 1,Item 2,+Item 3,Item 4;' + mxShapeMockupListBox.prototype.cst.TEXT_SIZE + '=17;' + mxShapeMockupListBox.prototype.cst.SELECTED_COLOR + '=#ddeeff;', 150, 200, '', 'List Box', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupPwField.prototype.cst.SHAPE_PW_FIELD + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxShapeMockupPwField.prototype.cst.MAIN_TEXT + '=********', 150, 30, '', 'Password Field', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupSplitter.prototype.cst.SHAPE_SPLITTER + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;', 350, 10, '', 'Horizontal Splitter', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupSplitter.prototype.cst.SHAPE_SPLITTER + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxConstants.STYLE_DIRECTION + '=' + mxConstants.DIRECTION_NORTH + ';', 10, 350, '', 'Vertical Splitter', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupWedgeBar.prototype.cst.SHAPE_WEDGE_BAR + ';' + mxConstants.STYLE_STROKECOLOR + '=#666666;' + mxShapeMockupWedgeBar.prototype.cst.STYLE_FILLCOLOR2 + '=#008cff;' + mxShapeMockupWedgeBar.prototype.cst.TEXT_COLOR + '=#666666;' + mxShapeMockupWedgeBar.prototype.cst.SEL_TEXT_COLOR + '=#ffffff;' + mxConstants.STYLE_FILLCOLOR + '=#ffffff;' + mxShapeMockupWedgeBar.prototype.cst.TAB_NAMES + '=Tab 1,+Tab 2,Tab 3;' + mxShapeMockupWedgeBar.prototype.cst.TEXT_SIZE + '=17;' + mxShapeMockupWedgeBar.prototype.cst.TAB_STYLE + '=' + mxShapeMockupWedgeBar.prototype.cst.BLOCK + ';', 400, 30, '', 'Wedge Bar', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=mxgraph.mockup.menus_and_buttons.font_style_selector_1;', 136, 31, '', 'Formatting Toolbar 1', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=mxgraph.mockup.menus_and_buttons.font_style_selector_2;', 235, 31, '', 'Formatting Toolbar 2', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=mxgraph.mockup.menus_and_buttons.font_style_selector_3;', 176, 38, '', 'Formatting Toolbar 3', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupSearchBox.prototype.cst.SHAPE_SEARCH_BOX + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxShapeMockupSearchBox.prototype.cst.MAIN_TEXT + '=Search;' + mxShapeMockupSearchBox.prototype.cst.STROKE_COLOR2 + '=#008cff;' + mxShapeMockupSearchBox.prototype.cst.TEXT_COLOR + '=#666666;' + mxShapeMockupSearchBox.prototype.cst.TEXT_SIZE + '=17;', 150, 30, '', 'Search Box', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupSignIn.prototype.cst.SHAPE_SIGN_IN + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxShapeMockupSignIn.prototype.cst.STROKE_COLOR2 + '=#ddeeff;' + mxShapeMockupSignIn.prototype.cst.TEXT_COLOR + '=#666666;' + mxShapeMockupSignIn.prototype.cst.MAIN_TEXT + '=Sign In,User Name:,johndoe,Password:,********,Forgot Password?,New User,SIGN IN,SIGN UP;' + mxShapeMockupSignIn.prototype.cst.TEXT_COLOR2 + '=#ffffff;' + mxShapeMockupSignIn.prototype.cst.TEXT_SIZE + '=12;' + mxShapeMockupSignIn.prototype.cst.TEXT_SIZE2 + '=15;' + mxShapeMockupSignIn.prototype.cst.FILL_COLOR2 + '=#66bbff;', 200, 300, '', 'Sign In', false));
			content.appendChild(this.createVertexTemplate(s + mxConstants.STYLE_SHAPE + '=' + mxShapeMockupCalendar.prototype.cst.SHAPE_CALENDAR + ';' + mxConstants.STYLE_STROKECOLOR + '=#999999;' + mxShapeMockupCalendar.prototype.cst.STROKE_COLOR2 + '=#008cff;' + mxShapeMockupCalendar.prototype.cst.MAIN_TEXT + '=April 2013;' + mxShapeMockupCalendar.prototype.cst.TEXT_SIZE + '=12;' + mxShapeMockupCalendar.prototype.cst.TEXT_COLOR + '=#999999;' + mxShapeMockupCalendar.prototype.cst.FIRST_DAY + '=0;' + mxShapeMockupCalendar.prototype.cst.START_ON + '=0;' + mxShapeMockupCalendar.prototype.cst.DAYS + '=30;' + mxShapeMockupCalendar.prototype.cst.PREV_DAYS + '=31;' + mxShapeMockupCalendar.prototype.cst.DAY_NAMES + '=Mo,Tu,We,Th,Fr,Sa,Su;' + mxShapeMockupCalendar.prototype.cst.SELECTED_DAY + '=24;' + mxShapeMockupCalendar.prototype.cst.TEXT_COLOR2 + '=#ffffff;', 160, 175, '', 'Calendar', false));
		}));
	};
})();
